window.STREAMING_PRODUCT_DATA = {
  "summary": {
    "modeled_rows": 7350,
    "daily_metric_rows": 7200,
    "experiment_rows": 60,
    "features": 12,
    "tests": 5,
    "avg_data_quality": 87.7,
    "top_priority": {
      "feature_id": "F002",
      "feature_name": "Personalized Top Picks",
      "product_area": "Home",
      "primary_device": "Connected TV",
      "service_tier": "SVOD",
      "business_owner": "ML Product",
      "launch_stage": "experiment",
      "active_accounts": 62150,
      "qualified_start_rate": 0.567,
      "avg_watch_minutes": 30.1,
      "conversion_rate": 0.2086,
      "day7_retention_rate": 0.2589,
      "playback_start_ms": 860,
      "rebuffer_rate": 0.013,
      "data_quality_score": 87.8,
      "experiment_lift_pct": 3.2,
      "confidence_score": 98.0,
      "priority_score": 1998.9,
      "next_move": "add to roadmap review"
    },
    "top_experiment": {
      "experiment_id": "EXP001",
      "feature_id": "F002",
      "feature_name": "Personalized Top Picks",
      "test_type": "A/B",
      "hypothesis": "Ranking personalization increases qualified starts without rebuffer regression.",
      "primary_metric": "qualified_start_rate",
      "avg_lift_pct": 3.2,
      "best_segment": "New trial households",
      "risk_segment": "Ad-supported explorers",
      "min_p_value": 0.0,
      "guardrail_delta_pct": 0.64,
      "data_quality_score": 87.8,
      "confidence_score": 98.0,
      "estimated_accounts_reached": 62150,
      "decision": "hold"
    },
    "trust_risk": {
      "feature_id": "F008",
      "feature_name": "Search Intent Rewrite",
      "check_type": "segment_join",
      "score": 68.5,
      "status": "fail",
      "owner": "data platform",
      "recommended_fix": "Document lineage owner"
    },
    "launch_recommendations": 1,
    "hold_recommendations": 2
  },
  "priorityQueue": [
    {
      "feature_id": "F002",
      "feature_name": "Personalized Top Picks",
      "product_area": "Home",
      "primary_device": "Connected TV",
      "service_tier": "SVOD",
      "business_owner": "ML Product",
      "launch_stage": "experiment",
      "active_accounts": 62150,
      "qualified_start_rate": 0.567,
      "avg_watch_minutes": 30.1,
      "conversion_rate": 0.2086,
      "day7_retention_rate": 0.2589,
      "playback_start_ms": 860,
      "rebuffer_rate": 0.013,
      "data_quality_score": 87.8,
      "experiment_lift_pct": 3.2,
      "confidence_score": 98.0,
      "priority_score": 1998.9,
      "next_move": "add to roadmap review"
    },
    {
      "feature_id": "F003",
      "feature_name": "Short Preview Autoplay",
      "product_area": "Discovery",
      "primary_device": "Mobile",
      "service_tier": "SVOD",
      "business_owner": "Growth",
      "launch_stage": "experiment",
      "active_accounts": 34738,
      "qualified_start_rate": 0.5702,
      "avg_watch_minutes": 30.1,
      "conversion_rate": 0.2091,
      "day7_retention_rate": 0.2597,
      "playback_start_ms": 660,
      "rebuffer_rate": 0.0169,
      "data_quality_score": 90.2,
      "experiment_lift_pct": 2.53,
      "confidence_score": 98.0,
      "priority_score": 925.6,
      "next_move": "ship with monitoring"
    },
    {
      "feature_id": "F001",
      "feature_name": "Continue Watching Rail",
      "product_area": "Home",
      "primary_device": "Connected TV",
      "service_tier": "SVOD",
      "business_owner": "Product",
      "launch_stage": "launched",
      "active_accounts": 62046,
      "qualified_start_rate": 0.5691,
      "avg_watch_minutes": 30.0,
      "conversion_rate": 0.2091,
      "day7_retention_rate": 0.2598,
      "playback_start_ms": 849,
      "rebuffer_rate": 0.013,
      "data_quality_score": 87.9,
      "experiment_lift_pct": 1.28,
      "confidence_score": 63.3,
      "priority_score": 904.5,
      "next_move": "add to roadmap review"
    },
    {
      "feature_id": "F004",
      "feature_name": "Sports Live Hub",
      "product_area": "Live",
      "primary_device": "Connected TV",
      "service_tier": "Ad Supported",
      "business_owner": "Live Product",
      "launch_stage": "beta",
      "active_accounts": 57823,
      "qualified_start_rate": 0.5566,
      "avg_watch_minutes": 30.4,
      "conversion_rate": 0.2108,
      "day7_retention_rate": 0.2579,
      "playback_start_ms": 872,
      "rebuffer_rate": 0.0136,
      "data_quality_score": 84.8,
      "experiment_lift_pct": 1.13,
      "confidence_score": 61.0,
      "priority_score": 765.9,
      "next_move": "add to roadmap review"
    },
    {
      "feature_id": "F008",
      "feature_name": "Search Intent Rewrite",
      "product_area": "Search",
      "primary_device": "Web",
      "service_tier": "SVOD",
      "business_owner": "Search",
      "launch_stage": "experiment",
      "active_accounts": 20625,
      "qualified_start_rate": 0.5714,
      "avg_watch_minutes": 30.3,
      "conversion_rate": 0.2087,
      "day7_retention_rate": 0.2607,
      "playback_start_ms": 613,
      "rebuffer_rate": 0.011,
      "data_quality_score": 80.1,
      "experiment_lift_pct": 3.08,
      "confidence_score": 98.0,
      "priority_score": 666.0,
      "next_move": "iterate experiment"
    },
    {
      "feature_id": "F007",
      "feature_name": "Ad Load Balancer",
      "product_area": "Ads",
      "primary_device": "Connected TV",
      "service_tier": "Ad Supported",
      "business_owner": "Ads Product",
      "launch_stage": "experiment",
      "active_accounts": 40714,
      "qualified_start_rate": 0.5638,
      "avg_watch_minutes": 29.9,
      "conversion_rate": 0.2081,
      "day7_retention_rate": 0.2596,
      "playback_start_ms": 855,
      "rebuffer_rate": 0.0136,
      "data_quality_score": 83.0,
      "experiment_lift_pct": 1.24,
      "confidence_score": 98.0,
      "priority_score": 601.8,
      "next_move": "add to roadmap review"
    },
    {
      "feature_id": "F011",
      "feature_name": "New Episode Reminder",
      "product_area": "Notifications",
      "primary_device": "Mobile",
      "service_tier": "SVOD",
      "business_owner": "Lifecycle",
      "launch_stage": "launched",
      "active_accounts": 26738,
      "qualified_start_rate": 0.5783,
      "avg_watch_minutes": 30.1,
      "conversion_rate": 0.2085,
      "day7_retention_rate": 0.2585,
      "playback_start_ms": 655,
      "rebuffer_rate": 0.0168,
      "data_quality_score": 88.3,
      "experiment_lift_pct": 1.53,
      "confidence_score": 98.0,
      "priority_score": 481.1,
      "next_move": "iterate experiment"
    },
    {
      "feature_id": "F009",
      "feature_name": "Household Switcher",
      "product_area": "Profiles",
      "primary_device": "Connected TV",
      "service_tier": "SVOD",
      "business_owner": "Identity",
      "launch_stage": "beta",
      "active_accounts": 37517,
      "qualified_start_rate": 0.5668,
      "avg_watch_minutes": 30.2,
      "conversion_rate": 0.2099,
      "day7_retention_rate": 0.258,
      "playback_start_ms": 856,
      "rebuffer_rate": 0.0128,
      "data_quality_score": 89.4,
      "experiment_lift_pct": 1.0,
      "confidence_score": 64.4,
      "priority_score": 463.8,
      "next_move": "add to roadmap review"
    }
  ],
  "experimentReadouts": [
    {
      "experiment_id": "EXP001",
      "feature_id": "F002",
      "feature_name": "Personalized Top Picks",
      "test_type": "A/B",
      "hypothesis": "Ranking personalization increases qualified starts without rebuffer regression.",
      "primary_metric": "qualified_start_rate",
      "avg_lift_pct": 3.2,
      "best_segment": "New trial households",
      "risk_segment": "Ad-supported explorers",
      "min_p_value": 0.0,
      "guardrail_delta_pct": 0.64,
      "data_quality_score": 87.8,
      "confidence_score": 98.0,
      "estimated_accounts_reached": 62150,
      "decision": "hold"
    },
    {
      "experiment_id": "EXP002",
      "feature_id": "F003",
      "feature_name": "Short Preview Autoplay",
      "test_type": "Multivariate",
      "hypothesis": "Preview length and audio state increase title discovery while keeping exits stable.",
      "primary_metric": "conversion_rate",
      "avg_lift_pct": 2.53,
      "best_segment": "New trial households",
      "risk_segment": "Ad-supported explorers",
      "min_p_value": 0.0,
      "guardrail_delta_pct": 0.39,
      "data_quality_score": 90.2,
      "confidence_score": 98.0,
      "estimated_accounts_reached": 34738,
      "decision": "launch"
    },
    {
      "experiment_id": "EXP003",
      "feature_id": "F007",
      "feature_name": "Ad Load Balancer",
      "test_type": "A/B",
      "hypothesis": "Ad pod spacing improves completion while protecting watch minutes.",
      "primary_metric": "day7_retention_rate",
      "avg_lift_pct": 1.24,
      "best_segment": "Kids co-viewing households",
      "risk_segment": "Ad-supported explorers",
      "min_p_value": 0.0,
      "guardrail_delta_pct": 1.19,
      "data_quality_score": 83.0,
      "confidence_score": 98.0,
      "estimated_accounts_reached": 40714,
      "decision": "hold"
    },
    {
      "experiment_id": "EXP004",
      "feature_id": "F008",
      "feature_name": "Search Intent Rewrite",
      "test_type": "Multivariate",
      "hypothesis": "Intent rewrite improves successful search sessions for ambiguous queries.",
      "primary_metric": "search_success_rate",
      "avg_lift_pct": 3.08,
      "best_segment": "Sports event viewers",
      "risk_segment": "Returning binge viewers",
      "min_p_value": 0.0,
      "guardrail_delta_pct": 0.38,
      "data_quality_score": 80.1,
      "confidence_score": 98.0,
      "estimated_accounts_reached": 20625,
      "decision": "iterate"
    },
    {
      "experiment_id": "EXP005",
      "feature_id": "F011",
      "feature_name": "New Episode Reminder",
      "test_type": "A/B",
      "hypothesis": "Reminder timing lifts day-seven retention for episodic viewers.",
      "primary_metric": "day7_retention_rate",
      "avg_lift_pct": 1.53,
      "best_segment": "Sports event viewers",
      "risk_segment": "Returning binge viewers",
      "min_p_value": 0.0,
      "guardrail_delta_pct": 0.42,
      "data_quality_score": 88.3,
      "confidence_score": 98.0,
      "estimated_accounts_reached": 26738,
      "decision": "iterate"
    }
  ],
  "segmentSummary": [
    {
      "customer_segment": "Returning binge viewers",
      "active_accounts": 89695,
      "avg_watch_minutes": 40.1,
      "conversion_rate": 0.2647,
      "day7_retention_rate": 0.3481,
      "highest_response_feature": "Personalized Top Picks"
    },
    {
      "customer_segment": "New trial households",
      "active_accounts": 89438,
      "avg_watch_minutes": 22.5,
      "conversion_rate": 0.1854,
      "day7_retention_rate": 0.2079,
      "highest_response_feature": "Personalized Top Picks"
    },
    {
      "customer_segment": "Sports event viewers",
      "active_accounts": 97702,
      "avg_watch_minutes": 33.0,
      "conversion_rate": 0.2257,
      "day7_retention_rate": 0.2462,
      "highest_response_feature": "Personalized Top Picks"
    },
    {
      "customer_segment": "Kids co-viewing households",
      "active_accounts": 89449,
      "avg_watch_minutes": 28.8,
      "conversion_rate": 0.2048,
      "day7_retention_rate": 0.3069,
      "highest_response_feature": "Personalized Top Picks"
    },
    {
      "customer_segment": "Ad-supported explorers",
      "active_accounts": 89730,
      "avg_watch_minutes": 26.2,
      "conversion_rate": 0.1645,
      "day7_retention_rate": 0.1873,
      "highest_response_feature": "Personalized Top Picks"
    }
  ],
  "trustQueue": [
    {
      "feature_id": "F008",
      "feature_name": "Search Intent Rewrite",
      "check_type": "segment_join",
      "score": 68.5,
      "status": "fail",
      "owner": "data platform",
      "recommended_fix": "Document lineage owner"
    },
    {
      "feature_id": "F007",
      "feature_name": "Ad Load Balancer",
      "check_type": "segment_join",
      "score": 72.9,
      "status": "fail",
      "owner": "product analytics",
      "recommended_fix": "Refresh segment mapping"
    },
    {
      "feature_id": "F008",
      "feature_name": "Search Intent Rewrite",
      "check_type": "duplicate_exposure",
      "score": 75.7,
      "status": "fail",
      "owner": "analytics engineering",
      "recommended_fix": "Certify metric definition"
    },
    {
      "feature_id": "F004",
      "feature_name": "Sports Live Hub",
      "check_type": "duplicate_exposure",
      "score": 77.0,
      "status": "fail",
      "owner": "experiment platform",
      "recommended_fix": "Add exposure dedupe test"
    },
    {
      "feature_id": "F007",
      "feature_name": "Ad Load Balancer",
      "check_type": "duplicate_exposure",
      "score": 78.3,
      "status": "fail",
      "owner": "product analytics",
      "recommended_fix": "Backfill missing events"
    },
    {
      "feature_id": "F008",
      "feature_name": "Search Intent Rewrite",
      "check_type": "freshness",
      "score": 79.4,
      "status": "fail",
      "owner": "data platform",
      "recommended_fix": "Backfill missing events"
    },
    {
      "feature_id": "F009",
      "feature_name": "Household Switcher",
      "check_type": "segment_join",
      "score": 82.2,
      "status": "watch",
      "owner": "experiment platform",
      "recommended_fix": "Certify metric definition"
    },
    {
      "feature_id": "F005",
      "feature_name": "Kids Profile Gate",
      "check_type": "metric_definition",
      "score": 82.3,
      "status": "watch",
      "owner": "product analytics",
      "recommended_fix": "Refresh segment mapping"
    },
    {
      "feature_id": "F002",
      "feature_name": "Personalized Top Picks",
      "check_type": "segment_join",
      "score": 83.0,
      "status": "watch",
      "owner": "product analytics",
      "recommended_fix": "Document lineage owner"
    },
    {
      "feature_id": "F012",
      "feature_name": "FAST Channel Guide",
      "check_type": "freshness",
      "score": 83.0,
      "status": "watch",
      "owner": "experiment platform",
      "recommended_fix": "Backfill missing events"
    }
  ],
  "metricDefinitions": [
    {
      "metric_name": "qualified_start_rate",
      "definition": "Qualified starts divided by sessions",
      "metric_role": "Primary engagement",
      "source_table": "Daily feature device mart",
      "owner": "product analytics"
    },
    {
      "metric_name": "day7_retention_rate",
      "definition": "Accounts active seven days after feature exposure divided by exposed accounts",
      "metric_role": "Retention",
      "source_table": "Experiment cohort table",
      "owner": "lifecycle analytics"
    },
    {
      "metric_name": "conversion_rate",
      "definition": "Target action completions divided by eligible exposed accounts",
      "metric_role": "Primary conversion",
      "source_table": "Experiment result table",
      "owner": "product analytics"
    },
    {
      "metric_name": "avg_watch_minutes",
      "definition": "Average watch minutes per active account",
      "metric_role": "Engagement depth",
      "source_table": "Playback fact table",
      "owner": "analytics engineering"
    },
    {
      "metric_name": "playback_start_ms",
      "definition": "Median playback startup latency in milliseconds",
      "metric_role": "Guardrail",
      "source_table": "Playback quality logs",
      "owner": "playback engineering"
    },
    {
      "metric_name": "rebuffer_rate",
      "definition": "Sessions with rebuffering divided by playback sessions",
      "metric_role": "Guardrail",
      "source_table": "Playback quality logs",
      "owner": "playback engineering"
    },
    {
      "metric_name": "search_success_rate",
      "definition": "Search sessions with a title detail view or play within ten minutes",
      "metric_role": "Discovery quality",
      "source_table": "Search event stream",
      "owner": "search product"
    },
    {
      "metric_name": "data_quality_score",
      "definition": "Weighted score from freshness, completeness, duplicate exposure, and join coverage checks",
      "metric_role": "Trust",
      "source_table": "Analytics quality checks",
      "owner": "data platform"
    }
  ],
  "stakeholderRequests": [
    {
      "request_id": "REQ001",
      "opened_date": "2026-04-18",
      "requester": "ad product lead",
      "feature_id": "F002",
      "question": "Which device segment should receive the next preview treatment?",
      "decision_needed": "launch decision",
      "urgency": "medium",
      "status": "queued"
    },
    {
      "request_id": "REQ002",
      "opened_date": "2026-03-12",
      "requester": "product manager",
      "feature_id": "F010",
      "question": "Which device segment should receive the next preview treatment?",
      "decision_needed": "roadmap priority",
      "urgency": "medium",
      "status": "needs data fix"
    },
    {
      "request_id": "REQ003",
      "opened_date": "2026-03-08",
      "requester": "ad product lead",
      "feature_id": "F006",
      "question": "Which retention movement is statistically reliable after reminders?",
      "decision_needed": "weekly business review",
      "urgency": "high",
      "status": "needs data fix"
    },
    {
      "request_id": "REQ004",
      "opened_date": "2026-04-18",
      "requester": "engineering manager",
      "feature_id": "F008",
      "question": "Which search cohorts explain the recent successful search decline?",
      "decision_needed": "weekly business review",
      "urgency": "medium",
      "status": "queued"
    },
    {
      "request_id": "REQ005",
      "opened_date": "2026-02-28",
      "requester": "content strategy",
      "feature_id": "F010",
      "question": "Where should the next roadmap review focus for feature cleanup?",
      "decision_needed": "weekly business review",
      "urgency": "high",
      "status": "answered"
    },
    {
      "request_id": "REQ006",
      "opened_date": "2026-04-13",
      "requester": "ad product lead",
      "feature_id": "F008",
      "question": "Which search cohorts explain the recent successful search decline?",
      "decision_needed": "roadmap priority",
      "urgency": "medium",
      "status": "queued"
    },
    {
      "request_id": "REQ007",
      "opened_date": "2026-03-01",
      "requester": "content strategy",
      "feature_id": "F008",
      "question": "Which retention movement is statistically reliable after reminders?",
      "decision_needed": "weekly business review",
      "urgency": "medium",
      "status": "queued"
    },
    {
      "request_id": "REQ008",
      "opened_date": "2026-03-13",
      "requester": "content strategy",
      "feature_id": "F006",
      "question": "Why did connected TV completion drop after live hub launch?",
      "decision_needed": "weekly business review",
      "urgency": "low",
      "status": "in analysis"
    }
  ]
};
